# BUILD STAGE

FROM golang:1.23 AS builder

WORKDIR /app

COPY src/go.mod src/go.sum ./

RUN go mod download

COPY src/ ./

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -o master master.go

# Runtime

FROM alpine:3.22

WORKDIR /app

COPY --from=builder /app/master .

EXPOSE 50051

CMD ["./master"]

