# BUILD STAGE

FROM golang:1.24 AS builder

ENV GOTOOLCHAIN=auto

WORKDIR /app

COPY src/go.mod src/go.sum ./

RUN go mod download

COPY src/ ./

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -o master ./cmd/master

# Runtime

FROM scratch

COPY --from=builder /app/master /master

EXPOSE 50051

CMD ["/master"]
