# BUILD STAGE

FROM golang:1.24 AS builder

ENV GOTOOLCHAIN=auto

WORKDIR /app

COPY src/go.mod src/go.sum ./

RUN go mod download

COPY src/ ./

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -o worker ./cmd/worker

# Runtime

FROM scratch

COPY --from=builder /app/worker /worker

EXPOSE 50051

CMD ["/worker"]
