// proto/mapreduce.proto
//
// Contratos de datos y protocolo de control del motor MapReduce.
//
// Los mensajes de negocio (sección 1) corresponden 1:1 a las tablas
// definidas en docs/03-esquema-datos.typ.
//
// Los mensajes de control (sección 2) cubren el protocolo del motor
// genérico: asignación de tareas, heartbeat, reporte de resultados
// y transferencia de datos durante el shuffle.
//
// Los servicios gRPC (sección 3) definen las interfaces entre master
// y workers.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: proto/mapreduce.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tipo de job dentro del pipeline de dos etapas.
type JobType int32

const (
	JobType_JOB_TYPE_UNSPECIFIED JobType = 0
	JobType_JOB_A_COMPETITION    JobType = 1 // Etapa 1: índice de competencia
	JobType_JOB_B1_PRICE         JobType = 2 // Etapa 1: desviación de precio
	JobType_JOB_B2_CONCENTRATION JobType = 3 // Etapa 1: concentración proveedor-entidad
	JobType_JOB_JOIN             JobType = 4 // Etapa 2: reduce-side join
)

// Enum value maps for JobType.
var (
	JobType_name = map[int32]string{
		0: "JOB_TYPE_UNSPECIFIED",
		1: "JOB_A_COMPETITION",
		2: "JOB_B1_PRICE",
		3: "JOB_B2_CONCENTRATION",
		4: "JOB_JOIN",
	}
	JobType_value = map[string]int32{
		"JOB_TYPE_UNSPECIFIED": 0,
		"JOB_A_COMPETITION":    1,
		"JOB_B1_PRICE":         2,
		"JOB_B2_CONCENTRATION": 3,
		"JOB_JOIN":             4,
	}
)

func (x JobType) Enum() *JobType {
	p := new(JobType)
	*p = x
	return p
}

func (x JobType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mapreduce_proto_enumTypes[0].Descriptor()
}

func (JobType) Type() protoreflect.EnumType {
	return &file_proto_mapreduce_proto_enumTypes[0]
}

func (x JobType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobType.Descriptor instead.
func (JobType) EnumDescriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{0}
}

// Fase de ejecución dentro de un job.
type TaskPhase int32

const (
	TaskPhase_TASK_PHASE_UNSPECIFIED TaskPhase = 0
	TaskPhase_PHASE_MAP              TaskPhase = 1
	TaskPhase_PHASE_SHUFFLE          TaskPhase = 2
	TaskPhase_PHASE_REDUCE           TaskPhase = 3
)

// Enum value maps for TaskPhase.
var (
	TaskPhase_name = map[int32]string{
		0: "TASK_PHASE_UNSPECIFIED",
		1: "PHASE_MAP",
		2: "PHASE_SHUFFLE",
		3: "PHASE_REDUCE",
	}
	TaskPhase_value = map[string]int32{
		"TASK_PHASE_UNSPECIFIED": 0,
		"PHASE_MAP":              1,
		"PHASE_SHUFFLE":          2,
		"PHASE_REDUCE":           3,
	}
)

func (x TaskPhase) Enum() *TaskPhase {
	p := new(TaskPhase)
	*p = x
	return p
}

func (x TaskPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mapreduce_proto_enumTypes[1].Descriptor()
}

func (TaskPhase) Type() protoreflect.EnumType {
	return &file_proto_mapreduce_proto_enumTypes[1]
}

func (x TaskPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskPhase.Descriptor instead.
func (TaskPhase) EnumDescriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{1}
}

// Estado de una tarea en la cola del master.
type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_PENDING            TaskStatus = 1
	TaskStatus_TASK_ASSIGNED           TaskStatus = 2
	TaskStatus_TASK_IN_PROGRESS        TaskStatus = 3
	TaskStatus_TASK_COMPLETED          TaskStatus = 4
	TaskStatus_TASK_FAILED             TaskStatus = 5
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_PENDING",
		2: "TASK_ASSIGNED",
		3: "TASK_IN_PROGRESS",
		4: "TASK_COMPLETED",
		5: "TASK_FAILED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_PENDING":            1,
		"TASK_ASSIGNED":           2,
		"TASK_IN_PROGRESS":        3,
		"TASK_COMPLETED":          4,
		"TASK_FAILED":             5,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mapreduce_proto_enumTypes[2].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_proto_mapreduce_proto_enumTypes[2]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{2}
}

// Registro individual de un chunk de Procesos de Contratación.
//
// Mapeo de columnas del CSV real (dataset p6dx-8zbt) a estos campos:
// proveedores_unicos_con_respuestas <- "proveedores_unicos_con" (Socrata
// trunca el fieldName real); nombre_entidad <- "entidad" (en este dataset
// la columna de nombre de entidad se llama distinto que en Contratos
// Electrónicos, que la llama "nombre_entidad").
type ProcessDataChunk struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	ChunkId                        string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	IdDelProceso                   string                 `protobuf:"bytes,2,opt,name=id_del_proceso,json=idDelProceso,proto3" json:"id_del_proceso,omitempty"`
	NitEntidad                     string                 `protobuf:"bytes,3,opt,name=nit_entidad,json=nitEntidad,proto3" json:"nit_entidad,omitempty"`
	ProveedoresInvitados           uint32                 `protobuf:"varint,4,opt,name=proveedores_invitados,json=proveedoresInvitados,proto3" json:"proveedores_invitados,omitempty"`
	ProveedoresUnicosConRespuestas uint32                 `protobuf:"varint,5,opt,name=proveedores_unicos_con_respuestas,json=proveedoresUnicosConRespuestas,proto3" json:"proveedores_unicos_con_respuestas,omitempty"`
	ModalidadDeContratacion        string                 `protobuf:"bytes,6,opt,name=modalidad_de_contratacion,json=modalidadDeContratacion,proto3" json:"modalidad_de_contratacion,omitempty"`
	EstadoDelProcedimiento         string                 `protobuf:"bytes,7,opt,name=estado_del_procedimiento,json=estadoDelProcedimiento,proto3" json:"estado_del_procedimiento,omitempty"`
	NombreEntidad                  string                 `protobuf:"bytes,8,opt,name=nombre_entidad,json=nombreEntidad,proto3" json:"nombre_entidad,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *ProcessDataChunk) Reset() {
	*x = ProcessDataChunk{}
	mi := &file_proto_mapreduce_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessDataChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessDataChunk) ProtoMessage() {}

func (x *ProcessDataChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessDataChunk.ProtoReflect.Descriptor instead.
func (*ProcessDataChunk) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessDataChunk) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *ProcessDataChunk) GetIdDelProceso() string {
	if x != nil {
		return x.IdDelProceso
	}
	return ""
}

func (x *ProcessDataChunk) GetNitEntidad() string {
	if x != nil {
		return x.NitEntidad
	}
	return ""
}

func (x *ProcessDataChunk) GetProveedoresInvitados() uint32 {
	if x != nil {
		return x.ProveedoresInvitados
	}
	return 0
}

func (x *ProcessDataChunk) GetProveedoresUnicosConRespuestas() uint32 {
	if x != nil {
		return x.ProveedoresUnicosConRespuestas
	}
	return 0
}

func (x *ProcessDataChunk) GetModalidadDeContratacion() string {
	if x != nil {
		return x.ModalidadDeContratacion
	}
	return ""
}

func (x *ProcessDataChunk) GetEstadoDelProcedimiento() string {
	if x != nil {
		return x.EstadoDelProcedimiento
	}
	return ""
}

func (x *ProcessDataChunk) GetNombreEntidad() string {
	if x != nil {
		return x.NombreEntidad
	}
	return ""
}

// Registro individual de un chunk de Contratos Electrónicos.
type ContractDataChunk struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	ChunkId                    string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	ProcesoDeCompra            string                 `protobuf:"bytes,2,opt,name=proceso_de_compra,json=procesoDeCompra,proto3" json:"proceso_de_compra,omitempty"`
	NitEntidad                 string                 `protobuf:"bytes,3,opt,name=nit_entidad,json=nitEntidad,proto3" json:"nit_entidad,omitempty"`
	DocumentoProveedor         string                 `protobuf:"bytes,4,opt,name=documento_proveedor,json=documentoProveedor,proto3" json:"documento_proveedor,omitempty"`
	ProveedorAdjudicado        string                 `protobuf:"bytes,5,opt,name=proveedor_adjudicado,json=proveedorAdjudicado,proto3" json:"proveedor_adjudicado,omitempty"`
	ValorDelContrato           uint64                 `protobuf:"varint,6,opt,name=valor_del_contrato,json=valorDelContrato,proto3" json:"valor_del_contrato,omitempty"`
	CodigoDeCategoriaPrincipal string                 `protobuf:"bytes,7,opt,name=codigo_de_categoria_principal,json=codigoDeCategoriaPrincipal,proto3" json:"codigo_de_categoria_principal,omitempty"`
	FechaDeFirma               string                 `protobuf:"bytes,8,opt,name=fecha_de_firma,json=fechaDeFirma,proto3" json:"fecha_de_firma,omitempty"`
	NombreEntidad              string                 `protobuf:"bytes,9,opt,name=nombre_entidad,json=nombreEntidad,proto3" json:"nombre_entidad,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *ContractDataChunk) Reset() {
	*x = ContractDataChunk{}
	mi := &file_proto_mapreduce_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractDataChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractDataChunk) ProtoMessage() {}

func (x *ContractDataChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractDataChunk.ProtoReflect.Descriptor instead.
func (*ContractDataChunk) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{1}
}

func (x *ContractDataChunk) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *ContractDataChunk) GetProcesoDeCompra() string {
	if x != nil {
		return x.ProcesoDeCompra
	}
	return ""
}

func (x *ContractDataChunk) GetNitEntidad() string {
	if x != nil {
		return x.NitEntidad
	}
	return ""
}

func (x *ContractDataChunk) GetDocumentoProveedor() string {
	if x != nil {
		return x.DocumentoProveedor
	}
	return ""
}

func (x *ContractDataChunk) GetProveedorAdjudicado() string {
	if x != nil {
		return x.ProveedorAdjudicado
	}
	return ""
}

func (x *ContractDataChunk) GetValorDelContrato() uint64 {
	if x != nil {
		return x.ValorDelContrato
	}
	return 0
}

func (x *ContractDataChunk) GetCodigoDeCategoriaPrincipal() string {
	if x != nil {
		return x.CodigoDeCategoriaPrincipal
	}
	return ""
}

func (x *ContractDataChunk) GetFechaDeFirma() string {
	if x != nil {
		return x.FechaDeFirma
	}
	return ""
}

func (x *ContractDataChunk) GetNombreEntidad() string {
	if x != nil {
		return x.NombreEntidad
	}
	return ""
}

// Job A: índice de competencia por proceso.
// Clave de agrupación: id_del_proceso.
type CompetitionMetrics struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	IdDelProceso            string                 `protobuf:"bytes,1,opt,name=id_del_proceso,json=idDelProceso,proto3" json:"id_del_proceso,omitempty"`
	NitEntidad              string                 `protobuf:"bytes,2,opt,name=nit_entidad,json=nitEntidad,proto3" json:"nit_entidad,omitempty"`
	ProveedoresInvitados    uint32                 `protobuf:"varint,3,opt,name=proveedores_invitados,json=proveedoresInvitados,proto3" json:"proveedores_invitados,omitempty"`
	ProveedoresResponden    uint32                 `protobuf:"varint,4,opt,name=proveedores_responden,json=proveedoresResponden,proto3" json:"proveedores_responden,omitempty"`
	IndiceCompetencia       float32                `protobuf:"fixed32,5,opt,name=indice_competencia,json=indiceCompetencia,proto3" json:"indice_competencia,omitempty"`
	ModalidadDeContratacion string                 `protobuf:"bytes,6,opt,name=modalidad_de_contratacion,json=modalidadDeContratacion,proto3" json:"modalidad_de_contratacion,omitempty"`
	EstadoDelProcedimiento  string                 `protobuf:"bytes,7,opt,name=estado_del_procedimiento,json=estadoDelProcedimiento,proto3" json:"estado_del_procedimiento,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *CompetitionMetrics) Reset() {
	*x = CompetitionMetrics{}
	mi := &file_proto_mapreduce_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompetitionMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitionMetrics) ProtoMessage() {}

func (x *CompetitionMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitionMetrics.ProtoReflect.Descriptor instead.
func (*CompetitionMetrics) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{2}
}

func (x *CompetitionMetrics) GetIdDelProceso() string {
	if x != nil {
		return x.IdDelProceso
	}
	return ""
}

func (x *CompetitionMetrics) GetNitEntidad() string {
	if x != nil {
		return x.NitEntidad
	}
	return ""
}

func (x *CompetitionMetrics) GetProveedoresInvitados() uint32 {
	if x != nil {
		return x.ProveedoresInvitados
	}
	return 0
}

func (x *CompetitionMetrics) GetProveedoresResponden() uint32 {
	if x != nil {
		return x.ProveedoresResponden
	}
	return 0
}

func (x *CompetitionMetrics) GetIndiceCompetencia() float32 {
	if x != nil {
		return x.IndiceCompetencia
	}
	return 0
}

func (x *CompetitionMetrics) GetModalidadDeContratacion() string {
	if x != nil {
		return x.ModalidadDeContratacion
	}
	return ""
}

func (x *CompetitionMetrics) GetEstadoDelProcedimiento() string {
	if x != nil {
		return x.EstadoDelProcedimiento
	}
	return ""
}

// Reduce B1: desviación de precio, agrupado por categoría UNSPSC.
// Clave de agrupación: categoria_unspsc.
type ContractPriceMetrics struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ProcesoDeCompra    string                 `protobuf:"bytes,1,opt,name=proceso_de_compra,json=procesoDeCompra,proto3" json:"proceso_de_compra,omitempty"`
	NitEntidad         string                 `protobuf:"bytes,2,opt,name=nit_entidad,json=nitEntidad,proto3" json:"nit_entidad,omitempty"`
	DocumentoProveedor string                 `protobuf:"bytes,3,opt,name=documento_proveedor,json=documentoProveedor,proto3" json:"documento_proveedor,omitempty"`
	ValorDelContrato   uint64                 `protobuf:"varint,4,opt,name=valor_del_contrato,json=valorDelContrato,proto3" json:"valor_del_contrato,omitempty"`
	CategoriaUnspsc    string                 `protobuf:"bytes,5,opt,name=categoria_unspsc,json=categoriaUnspsc,proto3" json:"categoria_unspsc,omitempty"`
	MedianaCategoria   uint64                 `protobuf:"varint,6,opt,name=mediana_categoria,json=medianaCategoria,proto3" json:"mediana_categoria,omitempty"`
	DesviacionPrecio   float32                `protobuf:"fixed32,7,opt,name=desviacion_precio,json=desviacionPrecio,proto3" json:"desviacion_precio,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ContractPriceMetrics) Reset() {
	*x = ContractPriceMetrics{}
	mi := &file_proto_mapreduce_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractPriceMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractPriceMetrics) ProtoMessage() {}

func (x *ContractPriceMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractPriceMetrics.ProtoReflect.Descriptor instead.
func (*ContractPriceMetrics) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{3}
}

func (x *ContractPriceMetrics) GetProcesoDeCompra() string {
	if x != nil {
		return x.ProcesoDeCompra
	}
	return ""
}

func (x *ContractPriceMetrics) GetNitEntidad() string {
	if x != nil {
		return x.NitEntidad
	}
	return ""
}

func (x *ContractPriceMetrics) GetDocumentoProveedor() string {
	if x != nil {
		return x.DocumentoProveedor
	}
	return ""
}

func (x *ContractPriceMetrics) GetValorDelContrato() uint64 {
	if x != nil {
		return x.ValorDelContrato
	}
	return 0
}

func (x *ContractPriceMetrics) GetCategoriaUnspsc() string {
	if x != nil {
		return x.CategoriaUnspsc
	}
	return ""
}

func (x *ContractPriceMetrics) GetMedianaCategoria() uint64 {
	if x != nil {
		return x.MedianaCategoria
	}
	return 0
}

func (x *ContractPriceMetrics) GetDesviacionPrecio() float32 {
	if x != nil {
		return x.DesviacionPrecio
	}
	return 0
}

// Reduce B2: concentración, agrupado por documento_proveedor + nit_entidad.
// Clave de agrupación: documento_proveedor + nit_entidad.
type ProviderConcentration struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	DocumentoProveedor        string                 `protobuf:"bytes,1,opt,name=documento_proveedor,json=documentoProveedor,proto3" json:"documento_proveedor,omitempty"`
	NitEntidad                string                 `protobuf:"bytes,2,opt,name=nit_entidad,json=nitEntidad,proto3" json:"nit_entidad,omitempty"`
	ContratosConEntidad       uint32                 `protobuf:"varint,3,opt,name=contratos_con_entidad,json=contratosConEntidad,proto3" json:"contratos_con_entidad,omitempty"`
	ContratosTotalesProveedor uint32                 `protobuf:"varint,4,opt,name=contratos_totales_proveedor,json=contratosTotalesProveedor,proto3" json:"contratos_totales_proveedor,omitempty"`
	ConcentracionProveedor    float32                `protobuf:"fixed32,5,opt,name=concentracion_proveedor,json=concentracionProveedor,proto3" json:"concentracion_proveedor,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ProviderConcentration) Reset() {
	*x = ProviderConcentration{}
	mi := &file_proto_mapreduce_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderConcentration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderConcentration) ProtoMessage() {}

func (x *ProviderConcentration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderConcentration.ProtoReflect.Descriptor instead.
func (*ProviderConcentration) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{4}
}

func (x *ProviderConcentration) GetDocumentoProveedor() string {
	if x != nil {
		return x.DocumentoProveedor
	}
	return ""
}

func (x *ProviderConcentration) GetNitEntidad() string {
	if x != nil {
		return x.NitEntidad
	}
	return ""
}

func (x *ProviderConcentration) GetContratosConEntidad() uint32 {
	if x != nil {
		return x.ContratosConEntidad
	}
	return 0
}

func (x *ProviderConcentration) GetContratosTotalesProveedor() uint32 {
	if x != nil {
		return x.ContratosTotalesProveedor
	}
	return 0
}

func (x *ProviderConcentration) GetConcentracionProveedor() float32 {
	if x != nil {
		return x.ConcentracionProveedor
	}
	return 0
}

// Un registro individual de riesgo por proceso.
// Los campos de contrato son opcionales (left outer join: procesos sin
// contrato se conservan con tiene_contrato = false).
type RiskRecord struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	IdDelProceso       string                 `protobuf:"bytes,1,opt,name=id_del_proceso,json=idDelProceso,proto3" json:"id_del_proceso,omitempty"`
	NitEntidad         string                 `protobuf:"bytes,2,opt,name=nit_entidad,json=nitEntidad,proto3" json:"nit_entidad,omitempty"`
	NombreEntidad      string                 `protobuf:"bytes,3,opt,name=nombre_entidad,json=nombreEntidad,proto3" json:"nombre_entidad,omitempty"`
	TieneContrato      bool                   `protobuf:"varint,4,opt,name=tiene_contrato,json=tieneContrato,proto3" json:"tiene_contrato,omitempty"`
	DocumentoProveedor string                 `protobuf:"bytes,5,opt,name=documento_proveedor,json=documentoProveedor,proto3" json:"documento_proveedor,omitempty"`
	NombreProveedor    string                 `protobuf:"bytes,6,opt,name=nombre_proveedor,json=nombreProveedor,proto3" json:"nombre_proveedor,omitempty"`
	ValorContrato      uint64                 `protobuf:"varint,7,opt,name=valor_contrato,json=valorContrato,proto3" json:"valor_contrato,omitempty"`
	IndiceCompetencia  float32                `protobuf:"fixed32,8,opt,name=indice_competencia,json=indiceCompetencia,proto3" json:"indice_competencia,omitempty"`
	DesviacionPrecio   float32                `protobuf:"fixed32,9,opt,name=desviacion_precio,json=desviacionPrecio,proto3" json:"desviacion_precio,omitempty"`
	Concentracion      float32                `protobuf:"fixed32,10,opt,name=concentracion,proto3" json:"concentracion,omitempty"`
	PuntuacionRiesgo   float32                `protobuf:"fixed32,11,opt,name=puntuacion_riesgo,json=puntuacionRiesgo,proto3" json:"puntuacion_riesgo,omitempty"`
	FlagRiesgoAlto     bool                   `protobuf:"varint,12,opt,name=flag_riesgo_alto,json=flagRiesgoAlto,proto3" json:"flag_riesgo_alto,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RiskRecord) Reset() {
	*x = RiskRecord{}
	mi := &file_proto_mapreduce_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskRecord) ProtoMessage() {}

func (x *RiskRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskRecord.ProtoReflect.Descriptor instead.
func (*RiskRecord) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{5}
}

func (x *RiskRecord) GetIdDelProceso() string {
	if x != nil {
		return x.IdDelProceso
	}
	return ""
}

func (x *RiskRecord) GetNitEntidad() string {
	if x != nil {
		return x.NitEntidad
	}
	return ""
}

func (x *RiskRecord) GetNombreEntidad() string {
	if x != nil {
		return x.NombreEntidad
	}
	return ""
}

func (x *RiskRecord) GetTieneContrato() bool {
	if x != nil {
		return x.TieneContrato
	}
	return false
}

func (x *RiskRecord) GetDocumentoProveedor() string {
	if x != nil {
		return x.DocumentoProveedor
	}
	return ""
}

func (x *RiskRecord) GetNombreProveedor() string {
	if x != nil {
		return x.NombreProveedor
	}
	return ""
}

func (x *RiskRecord) GetValorContrato() uint64 {
	if x != nil {
		return x.ValorContrato
	}
	return 0
}

func (x *RiskRecord) GetIndiceCompetencia() float32 {
	if x != nil {
		return x.IndiceCompetencia
	}
	return 0
}

func (x *RiskRecord) GetDesviacionPrecio() float32 {
	if x != nil {
		return x.DesviacionPrecio
	}
	return 0
}

func (x *RiskRecord) GetConcentracion() float32 {
	if x != nil {
		return x.Concentracion
	}
	return 0
}

func (x *RiskRecord) GetPuntuacionRiesgo() float32 {
	if x != nil {
		return x.PuntuacionRiesgo
	}
	return 0
}

func (x *RiskRecord) GetFlagRiesgoAlto() bool {
	if x != nil {
		return x.FlagRiesgoAlto
	}
	return false
}

// Resultado consolidado de un trabajo de análisis de riesgo.
type RiskAnalysisResult struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	JobId                   string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ExecutionTimeMs         uint64                 `protobuf:"varint,2,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	TotalProcesosAnalizados uint64                 `protobuf:"varint,3,opt,name=total_procesos_analizados,json=totalProcesosAnalizados,proto3" json:"total_procesos_analizados,omitempty"`
	TotalProcesosAltoRiesgo uint64                 `protobuf:"varint,4,opt,name=total_procesos_alto_riesgo,json=totalProcesosAltoRiesgo,proto3" json:"total_procesos_alto_riesgo,omitempty"`
	RegistrosRiesgo         []*RiskRecord          `protobuf:"bytes,5,rep,name=registros_riesgo,json=registrosRiesgo,proto3" json:"registros_riesgo,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RiskAnalysisResult) Reset() {
	*x = RiskAnalysisResult{}
	mi := &file_proto_mapreduce_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskAnalysisResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskAnalysisResult) ProtoMessage() {}

func (x *RiskAnalysisResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskAnalysisResult.ProtoReflect.Descriptor instead.
func (*RiskAnalysisResult) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{6}
}

func (x *RiskAnalysisResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RiskAnalysisResult) GetExecutionTimeMs() uint64 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

func (x *RiskAnalysisResult) GetTotalProcesosAnalizados() uint64 {
	if x != nil {
		return x.TotalProcesosAnalizados
	}
	return 0
}

func (x *RiskAnalysisResult) GetTotalProcesosAltoRiesgo() uint64 {
	if x != nil {
		return x.TotalProcesosAltoRiesgo
	}
	return 0
}

func (x *RiskAnalysisResult) GetRegistrosRiesgo() []*RiskRecord {
	if x != nil {
		return x.RegistrosRiesgo
	}
	return nil
}

// El master asigna un chunk a un worker para procesamiento.
type TaskAssignment struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskId          string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                            // Identificador único de la tarea
	ChunkId         string                 `protobuf:"bytes,2,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`                         // Identificador del chunk a procesar
	JobType         JobType                `protobuf:"varint,3,opt,name=job_type,json=jobType,proto3,enum=mapreduce.JobType" json:"job_type,omitempty"` // Qué job ejecutar
	Phase           TaskPhase              `protobuf:"varint,4,opt,name=phase,proto3,enum=mapreduce.TaskPhase" json:"phase,omitempty"`                  // En qué fase (map, shuffle, reduce)
	ProcessRecords  []*ProcessDataChunk    `protobuf:"bytes,5,rep,name=process_records,json=processRecords,proto3" json:"process_records,omitempty"`    // Datos si job A
	ContractRecords []*ContractDataChunk   `protobuf:"bytes,6,rep,name=contract_records,json=contractRecords,proto3" json:"contract_records,omitempty"` // Datos si job B1/B2
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskAssignment) Reset() {
	*x = TaskAssignment{}
	mi := &file_proto_mapreduce_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAssignment) ProtoMessage() {}

func (x *TaskAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAssignment.ProtoReflect.Descriptor instead.
func (*TaskAssignment) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{7}
}

func (x *TaskAssignment) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskAssignment) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *TaskAssignment) GetJobType() JobType {
	if x != nil {
		return x.JobType
	}
	return JobType_JOB_TYPE_UNSPECIFIED
}

func (x *TaskAssignment) GetPhase() TaskPhase {
	if x != nil {
		return x.Phase
	}
	return TaskPhase_TASK_PHASE_UNSPECIFIED
}

func (x *TaskAssignment) GetProcessRecords() []*ProcessDataChunk {
	if x != nil {
		return x.ProcessRecords
	}
	return nil
}

func (x *TaskAssignment) GetContractRecords() []*ContractDataChunk {
	if x != nil {
		return x.ContractRecords
	}
	return nil
}

type TaskAssignmentAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskAssignmentAck) Reset() {
	*x = TaskAssignmentAck{}
	mi := &file_proto_mapreduce_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAssignmentAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAssignmentAck) ProtoMessage() {}

func (x *TaskAssignmentAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAssignmentAck.ProtoReflect.Descriptor instead.
func (*TaskAssignmentAck) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{8}
}

func (x *TaskAssignmentAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *TaskAssignmentAck) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *TaskAssignmentAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Heartbeat periódico del worker al master.
// El master usa la ausencia de heartbeat para detectar workers caídos
// (timeout configurable, meta ≤ 10s de detección según 01-alcance.typ).
type HeartbeatRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	WorkerId          string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	CurrentTaskId     string                 `protobuf:"bytes,2,opt,name=current_task_id,json=currentTaskId,proto3" json:"current_task_id,omitempty"` // Vacío si el worker está idle
	CurrentTaskStatus TaskStatus             `protobuf:"varint,3,opt,name=current_task_status,json=currentTaskStatus,proto3,enum=mapreduce.TaskStatus" json:"current_task_status,omitempty"`
	ProgressPercent   float32                `protobuf:"fixed32,4,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"` // 0.0 a 1.0
	TimestampMs       int64                  `protobuf:"varint,5,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`              // Unix millis
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_mapreduce_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{9}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetCurrentTaskId() string {
	if x != nil {
		return x.CurrentTaskId
	}
	return ""
}

func (x *HeartbeatRequest) GetCurrentTaskStatus() TaskStatus {
	if x != nil {
		return x.CurrentTaskStatus
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *HeartbeatRequest) GetProgressPercent() float32 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *HeartbeatRequest) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_mapreduce_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{10}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

// El worker reporta la finalización (exitosa o fallida) de una tarea.
type TaskResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskId          string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkerId        string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Status          TaskStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=mapreduce.TaskStatus" json:"status,omitempty"`                  // TASK_COMPLETED o TASK_FAILED
	ErrorMessage    string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`             // Mensaje de error si TASK_FAILED
	ExecutionTimeMs int64                  `protobuf:"varint,5,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"` // Duración del procesamiento
	// Resultados intermedios según el job y la fase.
	// Solo uno de estos campos estará poblado según el job ejecutado.
	CompetitionResults   []*CompetitionMetrics    `protobuf:"bytes,6,rep,name=competition_results,json=competitionResults,proto3" json:"competition_results,omitempty"`
	PriceResults         []*ContractPriceMetrics  `protobuf:"bytes,7,rep,name=price_results,json=priceResults,proto3" json:"price_results,omitempty"`
	ConcentrationResults []*ProviderConcentration `protobuf:"bytes,8,rep,name=concentration_results,json=concentrationResults,proto3" json:"concentration_results,omitempty"`
	RiskResults          []*RiskRecord            `protobuf:"bytes,9,rep,name=risk_results,json=riskResults,proto3" json:"risk_results,omitempty"` // Para la Etapa 2 (join)
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_proto_mapreduce_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{11}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *TaskResult) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *TaskResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskResult) GetExecutionTimeMs() int64 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

func (x *TaskResult) GetCompetitionResults() []*CompetitionMetrics {
	if x != nil {
		return x.CompetitionResults
	}
	return nil
}

func (x *TaskResult) GetPriceResults() []*ContractPriceMetrics {
	if x != nil {
		return x.PriceResults
	}
	return nil
}

func (x *TaskResult) GetConcentrationResults() []*ProviderConcentration {
	if x != nil {
		return x.ConcentrationResults
	}
	return nil
}

func (x *TaskResult) GetRiskResults() []*RiskRecord {
	if x != nil {
		return x.RiskResults
	}
	return nil
}

type TaskResultAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResultAck) Reset() {
	*x = TaskResultAck{}
	mi := &file_proto_mapreduce_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResultAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResultAck) ProtoMessage() {}

func (x *TaskResultAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResultAck.ProtoReflect.Descriptor instead.
func (*TaskResultAck) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{12}
}

func (x *TaskResultAck) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *TaskResultAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Par clave-valor intermedio para transferencia durante el shuffle.
// La clave determina a qué worker de Reduce se dirige el registro.
// El valor contiene el registro intermedio según el job.
type ShuffleEntry struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Key     string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // Clave de agrupación (id_del_proceso, categoria_unspsc, etc.)
	JobType JobType                `protobuf:"varint,2,opt,name=job_type,json=jobType,proto3,enum=mapreduce.JobType" json:"job_type,omitempty"`
	// Exactamente uno de estos campos estará poblado según el job.
	Competition   *CompetitionMetrics    `protobuf:"bytes,3,opt,name=competition,proto3" json:"competition,omitempty"`
	Price         *ContractPriceMetrics  `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	Concentration *ProviderConcentration `protobuf:"bytes,5,opt,name=concentration,proto3" json:"concentration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShuffleEntry) Reset() {
	*x = ShuffleEntry{}
	mi := &file_proto_mapreduce_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShuffleEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShuffleEntry) ProtoMessage() {}

func (x *ShuffleEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShuffleEntry.ProtoReflect.Descriptor instead.
func (*ShuffleEntry) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{13}
}

func (x *ShuffleEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ShuffleEntry) GetJobType() JobType {
	if x != nil {
		return x.JobType
	}
	return JobType_JOB_TYPE_UNSPECIFIED
}

func (x *ShuffleEntry) GetCompetition() *CompetitionMetrics {
	if x != nil {
		return x.Competition
	}
	return nil
}

func (x *ShuffleEntry) GetPrice() *ContractPriceMetrics {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *ShuffleEntry) GetConcentration() *ProviderConcentration {
	if x != nil {
		return x.Concentration
	}
	return nil
}

// Solicitud de transferencia de un lote de pares clave-valor.
type ShuffleRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SourceWorkerId string                 `protobuf:"bytes,1,opt,name=source_worker_id,json=sourceWorkerId,proto3" json:"source_worker_id,omitempty"`
	TargetWorkerId string                 `protobuf:"bytes,2,opt,name=target_worker_id,json=targetWorkerId,proto3" json:"target_worker_id,omitempty"`
	Entries        []*ShuffleEntry        `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ShuffleRequest) Reset() {
	*x = ShuffleRequest{}
	mi := &file_proto_mapreduce_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShuffleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShuffleRequest) ProtoMessage() {}

func (x *ShuffleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShuffleRequest.ProtoReflect.Descriptor instead.
func (*ShuffleRequest) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{14}
}

func (x *ShuffleRequest) GetSourceWorkerId() string {
	if x != nil {
		return x.SourceWorkerId
	}
	return ""
}

func (x *ShuffleRequest) GetTargetWorkerId() string {
	if x != nil {
		return x.TargetWorkerId
	}
	return ""
}

func (x *ShuffleRequest) GetEntries() []*ShuffleEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ShuffleResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged    bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	RecordsReceived uint32                 `protobuf:"varint,2,opt,name=records_received,json=recordsReceived,proto3" json:"records_received,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ShuffleResponse) Reset() {
	*x = ShuffleResponse{}
	mi := &file_proto_mapreduce_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShuffleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShuffleResponse) ProtoMessage() {}

func (x *ShuffleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShuffleResponse.ProtoReflect.Descriptor instead.
func (*ShuffleResponse) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{15}
}

func (x *ShuffleResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *ShuffleResponse) GetRecordsReceived() uint32 {
	if x != nil {
		return x.RecordsReceived
	}
	return 0
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_mapreduce_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{16}
}

func (x *PingRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_mapreduce_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{17}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_mapreduce_proto protoreflect.FileDescriptor

const file_proto_mapreduce_proto_rawDesc = "" +
	"\n" +
	"\x15proto/mapreduce.proto\x12\tmapreduce\"\x91\x03\n" +
	"\x10ProcessDataChunk\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12$\n" +
	"\x0eid_del_proceso\x18\x02 \x01(\tR\fidDelProceso\x12\x1f\n" +
	"\vnit_entidad\x18\x03 \x01(\tR\n" +
	"nitEntidad\x123\n" +
	"\x15proveedores_invitados\x18\x04 \x01(\rR\x14proveedoresInvitados\x12I\n" +
	"!proveedores_unicos_con_respuestas\x18\x05 \x01(\rR\x1eproveedoresUnicosConRespuestas\x12:\n" +
	"\x19modalidad_de_contratacion\x18\x06 \x01(\tR\x17modalidadDeContratacion\x128\n" +
	"\x18estado_del_procedimiento\x18\a \x01(\tR\x16estadoDelProcedimiento\x12%\n" +
	"\x0enombre_entidad\x18\b \x01(\tR\rnombreEntidad\"\x9d\x03\n" +
	"\x11ContractDataChunk\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12*\n" +
	"\x11proceso_de_compra\x18\x02 \x01(\tR\x0fprocesoDeCompra\x12\x1f\n" +
	"\vnit_entidad\x18\x03 \x01(\tR\n" +
	"nitEntidad\x12/\n" +
	"\x13documento_proveedor\x18\x04 \x01(\tR\x12documentoProveedor\x121\n" +
	"\x14proveedor_adjudicado\x18\x05 \x01(\tR\x13proveedorAdjudicado\x12,\n" +
	"\x12valor_del_contrato\x18\x06 \x01(\x04R\x10valorDelContrato\x12A\n" +
	"\x1dcodigo_de_categoria_principal\x18\a \x01(\tR\x1acodigoDeCategoriaPrincipal\x12$\n" +
	"\x0efecha_de_firma\x18\b \x01(\tR\ffechaDeFirma\x12%\n" +
	"\x0enombre_entidad\x18\t \x01(\tR\rnombreEntidad\"\xea\x02\n" +
	"\x12CompetitionMetrics\x12$\n" +
	"\x0eid_del_proceso\x18\x01 \x01(\tR\fidDelProceso\x12\x1f\n" +
	"\vnit_entidad\x18\x02 \x01(\tR\n" +
	"nitEntidad\x123\n" +
	"\x15proveedores_invitados\x18\x03 \x01(\rR\x14proveedoresInvitados\x123\n" +
	"\x15proveedores_responden\x18\x04 \x01(\rR\x14proveedoresResponden\x12-\n" +
	"\x12indice_competencia\x18\x05 \x01(\x02R\x11indiceCompetencia\x12:\n" +
	"\x19modalidad_de_contratacion\x18\x06 \x01(\tR\x17modalidadDeContratacion\x128\n" +
	"\x18estado_del_procedimiento\x18\a \x01(\tR\x16estadoDelProcedimiento\"\xc7\x02\n" +
	"\x14ContractPriceMetrics\x12*\n" +
	"\x11proceso_de_compra\x18\x01 \x01(\tR\x0fprocesoDeCompra\x12\x1f\n" +
	"\vnit_entidad\x18\x02 \x01(\tR\n" +
	"nitEntidad\x12/\n" +
	"\x13documento_proveedor\x18\x03 \x01(\tR\x12documentoProveedor\x12,\n" +
	"\x12valor_del_contrato\x18\x04 \x01(\x04R\x10valorDelContrato\x12)\n" +
	"\x10categoria_unspsc\x18\x05 \x01(\tR\x0fcategoriaUnspsc\x12+\n" +
	"\x11mediana_categoria\x18\x06 \x01(\x04R\x10medianaCategoria\x12+\n" +
	"\x11desviacion_precio\x18\a \x01(\x02R\x10desviacionPrecio\"\x96\x02\n" +
	"\x15ProviderConcentration\x12/\n" +
	"\x13documento_proveedor\x18\x01 \x01(\tR\x12documentoProveedor\x12\x1f\n" +
	"\vnit_entidad\x18\x02 \x01(\tR\n" +
	"nitEntidad\x122\n" +
	"\x15contratos_con_entidad\x18\x03 \x01(\rR\x13contratosConEntidad\x12>\n" +
	"\x1bcontratos_totales_proveedor\x18\x04 \x01(\rR\x19contratosTotalesProveedor\x127\n" +
	"\x17concentracion_proveedor\x18\x05 \x01(\x02R\x16concentracionProveedor\"\xfd\x03\n" +
	"\n" +
	"RiskRecord\x12$\n" +
	"\x0eid_del_proceso\x18\x01 \x01(\tR\fidDelProceso\x12\x1f\n" +
	"\vnit_entidad\x18\x02 \x01(\tR\n" +
	"nitEntidad\x12%\n" +
	"\x0enombre_entidad\x18\x03 \x01(\tR\rnombreEntidad\x12%\n" +
	"\x0etiene_contrato\x18\x04 \x01(\bR\rtieneContrato\x12/\n" +
	"\x13documento_proveedor\x18\x05 \x01(\tR\x12documentoProveedor\x12)\n" +
	"\x10nombre_proveedor\x18\x06 \x01(\tR\x0fnombreProveedor\x12%\n" +
	"\x0evalor_contrato\x18\a \x01(\x04R\rvalorContrato\x12-\n" +
	"\x12indice_competencia\x18\b \x01(\x02R\x11indiceCompetencia\x12+\n" +
	"\x11desviacion_precio\x18\t \x01(\x02R\x10desviacionPrecio\x12$\n" +
	"\rconcentracion\x18\n" +
	" \x01(\x02R\rconcentracion\x12+\n" +
	"\x11puntuacion_riesgo\x18\v \x01(\x02R\x10puntuacionRiesgo\x12(\n" +
	"\x10flag_riesgo_alto\x18\f \x01(\bR\x0eflagRiesgoAlto\"\x92\x02\n" +
	"\x12RiskAnalysisResult\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12*\n" +
	"\x11execution_time_ms\x18\x02 \x01(\x04R\x0fexecutionTimeMs\x12:\n" +
	"\x19total_procesos_analizados\x18\x03 \x01(\x04R\x17totalProcesosAnalizados\x12;\n" +
	"\x1atotal_procesos_alto_riesgo\x18\x04 \x01(\x04R\x17totalProcesosAltoRiesgo\x12@\n" +
	"\x10registros_riesgo\x18\x05 \x03(\v2\x15.mapreduce.RiskRecordR\x0fregistrosRiesgo\"\xae\x02\n" +
	"\x0eTaskAssignment\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x19\n" +
	"\bchunk_id\x18\x02 \x01(\tR\achunkId\x12-\n" +
	"\bjob_type\x18\x03 \x01(\x0e2\x12.mapreduce.JobTypeR\ajobType\x12*\n" +
	"\x05phase\x18\x04 \x01(\x0e2\x14.mapreduce.TaskPhaseR\x05phase\x12D\n" +
	"\x0fprocess_records\x18\x05 \x03(\v2\x1b.mapreduce.ProcessDataChunkR\x0eprocessRecords\x12G\n" +
	"\x10contract_records\x18\x06 \x03(\v2\x1c.mapreduce.ContractDataChunkR\x0fcontractRecords\"f\n" +
	"\x11TaskAssignmentAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xec\x01\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12&\n" +
	"\x0fcurrent_task_id\x18\x02 \x01(\tR\rcurrentTaskId\x12E\n" +
	"\x13current_task_status\x18\x03 \x01(\x0e2\x15.mapreduce.TaskStatusR\x11currentTaskStatus\x12)\n" +
	"\x10progress_percent\x18\x04 \x01(\x02R\x0fprogressPercent\x12!\n" +
	"\ftimestamp_ms\x18\x05 \x01(\x03R\vtimestampMs\"7\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"\xe9\x03\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12-\n" +
	"\x06status\x18\x03 \x01(\x0e2\x15.mapreduce.TaskStatusR\x06status\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12*\n" +
	"\x11execution_time_ms\x18\x05 \x01(\x03R\x0fexecutionTimeMs\x12N\n" +
	"\x13competition_results\x18\x06 \x03(\v2\x1d.mapreduce.CompetitionMetricsR\x12competitionResults\x12D\n" +
	"\rprice_results\x18\a \x03(\v2\x1f.mapreduce.ContractPriceMetricsR\fpriceResults\x12U\n" +
	"\x15concentration_results\x18\b \x03(\v2 .mapreduce.ProviderConcentrationR\x14concentrationResults\x128\n" +
	"\frisk_results\x18\t \x03(\v2\x15.mapreduce.RiskRecordR\vriskResults\"M\n" +
	"\rTaskResultAck\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x8f\x02\n" +
	"\fShuffleEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\bjob_type\x18\x02 \x01(\x0e2\x12.mapreduce.JobTypeR\ajobType\x12?\n" +
	"\vcompetition\x18\x03 \x01(\v2\x1d.mapreduce.CompetitionMetricsR\vcompetition\x125\n" +
	"\x05price\x18\x04 \x01(\v2\x1f.mapreduce.ContractPriceMetricsR\x05price\x12F\n" +
	"\rconcentration\x18\x05 \x01(\v2 .mapreduce.ProviderConcentrationR\rconcentration\"\x97\x01\n" +
	"\x0eShuffleRequest\x12(\n" +
	"\x10source_worker_id\x18\x01 \x01(\tR\x0esourceWorkerId\x12(\n" +
	"\x10target_worker_id\x18\x02 \x01(\tR\x0etargetWorkerId\x121\n" +
	"\aentries\x18\x03 \x03(\v2\x17.mapreduce.ShuffleEntryR\aentries\"`\n" +
	"\x0fShuffleResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12)\n" +
	"\x10records_received\x18\x02 \x01(\rR\x0frecordsReceived\"!\n" +
	"\vPingRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage*t\n" +
	"\aJobType\x12\x18\n" +
	"\x14JOB_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11JOB_A_COMPETITION\x10\x01\x12\x10\n" +
	"\fJOB_B1_PRICE\x10\x02\x12\x18\n" +
	"\x14JOB_B2_CONCENTRATION\x10\x03\x12\f\n" +
	"\bJOB_JOIN\x10\x04*[\n" +
	"\tTaskPhase\x12\x1a\n" +
	"\x16TASK_PHASE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tPHASE_MAP\x10\x01\x12\x11\n" +
	"\rPHASE_SHUFFLE\x10\x02\x12\x10\n" +
	"\fPHASE_REDUCE\x10\x03*\x89\x01\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fTASK_PENDING\x10\x01\x12\x11\n" +
	"\rTASK_ASSIGNED\x10\x02\x12\x14\n" +
	"\x10TASK_IN_PROGRESS\x10\x03\x12\x12\n" +
	"\x0eTASK_COMPLETED\x10\x04\x12\x0f\n" +
	"\vTASK_FAILED\x10\x052\x9c\x01\n" +
	"\rMasterService\x12F\n" +
	"\tHeartbeat\x12\x1b.mapreduce.HeartbeatRequest\x1a\x1c.mapreduce.HeartbeatResponse\x12C\n" +
	"\x10ReportTaskResult\x12\x15.mapreduce.TaskResult\x1a\x18.mapreduce.TaskResultAck2\xdc\x01\n" +
	"\rWorkerService\x127\n" +
	"\x04Ping\x12\x16.mapreduce.PingRequest\x1a\x17.mapreduce.PingResponse\x12E\n" +
	"\n" +
	"AssignTask\x12\x19.mapreduce.TaskAssignment\x1a\x1c.mapreduce.TaskAssignmentAck\x12K\n" +
	"\x12ReceiveShuffleData\x12\x19.mapreduce.ShuffleRequest\x1a\x1a.mapreduce.ShuffleResponseB5Z3github.com/SalomonAvila/DistributedProcessing/protob\x06proto3"

var (
	file_proto_mapreduce_proto_rawDescOnce sync.Once
	file_proto_mapreduce_proto_rawDescData []byte
)

func file_proto_mapreduce_proto_rawDescGZIP() []byte {
	file_proto_mapreduce_proto_rawDescOnce.Do(func() {
		file_proto_mapreduce_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mapreduce_proto_rawDesc), len(file_proto_mapreduce_proto_rawDesc)))
	})
	return file_proto_mapreduce_proto_rawDescData
}

var file_proto_mapreduce_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_mapreduce_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_mapreduce_proto_goTypes = []any{
	(JobType)(0),                  // 0: mapreduce.JobType
	(TaskPhase)(0),                // 1: mapreduce.TaskPhase
	(TaskStatus)(0),               // 2: mapreduce.TaskStatus
	(*ProcessDataChunk)(nil),      // 3: mapreduce.ProcessDataChunk
	(*ContractDataChunk)(nil),     // 4: mapreduce.ContractDataChunk
	(*CompetitionMetrics)(nil),    // 5: mapreduce.CompetitionMetrics
	(*ContractPriceMetrics)(nil),  // 6: mapreduce.ContractPriceMetrics
	(*ProviderConcentration)(nil), // 7: mapreduce.ProviderConcentration
	(*RiskRecord)(nil),            // 8: mapreduce.RiskRecord
	(*RiskAnalysisResult)(nil),    // 9: mapreduce.RiskAnalysisResult
	(*TaskAssignment)(nil),        // 10: mapreduce.TaskAssignment
	(*TaskAssignmentAck)(nil),     // 11: mapreduce.TaskAssignmentAck
	(*HeartbeatRequest)(nil),      // 12: mapreduce.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 13: mapreduce.HeartbeatResponse
	(*TaskResult)(nil),            // 14: mapreduce.TaskResult
	(*TaskResultAck)(nil),         // 15: mapreduce.TaskResultAck
	(*ShuffleEntry)(nil),          // 16: mapreduce.ShuffleEntry
	(*ShuffleRequest)(nil),        // 17: mapreduce.ShuffleRequest
	(*ShuffleResponse)(nil),       // 18: mapreduce.ShuffleResponse
	(*PingRequest)(nil),           // 19: mapreduce.PingRequest
	(*PingResponse)(nil),          // 20: mapreduce.PingResponse
}
var file_proto_mapreduce_proto_depIdxs = []int32{
	8,  // 0: mapreduce.RiskAnalysisResult.registros_riesgo:type_name -> mapreduce.RiskRecord
	0,  // 1: mapreduce.TaskAssignment.job_type:type_name -> mapreduce.JobType
	1,  // 2: mapreduce.TaskAssignment.phase:type_name -> mapreduce.TaskPhase
	3,  // 3: mapreduce.TaskAssignment.process_records:type_name -> mapreduce.ProcessDataChunk
	4,  // 4: mapreduce.TaskAssignment.contract_records:type_name -> mapreduce.ContractDataChunk
	2,  // 5: mapreduce.HeartbeatRequest.current_task_status:type_name -> mapreduce.TaskStatus
	2,  // 6: mapreduce.TaskResult.status:type_name -> mapreduce.TaskStatus
	5,  // 7: mapreduce.TaskResult.competition_results:type_name -> mapreduce.CompetitionMetrics
	6,  // 8: mapreduce.TaskResult.price_results:type_name -> mapreduce.ContractPriceMetrics
	7,  // 9: mapreduce.TaskResult.concentration_results:type_name -> mapreduce.ProviderConcentration
	8,  // 10: mapreduce.TaskResult.risk_results:type_name -> mapreduce.RiskRecord
	0,  // 11: mapreduce.ShuffleEntry.job_type:type_name -> mapreduce.JobType
	5,  // 12: mapreduce.ShuffleEntry.competition:type_name -> mapreduce.CompetitionMetrics
	6,  // 13: mapreduce.ShuffleEntry.price:type_name -> mapreduce.ContractPriceMetrics
	7,  // 14: mapreduce.ShuffleEntry.concentration:type_name -> mapreduce.ProviderConcentration
	16, // 15: mapreduce.ShuffleRequest.entries:type_name -> mapreduce.ShuffleEntry
	12, // 16: mapreduce.MasterService.Heartbeat:input_type -> mapreduce.HeartbeatRequest
	14, // 17: mapreduce.MasterService.ReportTaskResult:input_type -> mapreduce.TaskResult
	19, // 18: mapreduce.WorkerService.Ping:input_type -> mapreduce.PingRequest
	10, // 19: mapreduce.WorkerService.AssignTask:input_type -> mapreduce.TaskAssignment
	17, // 20: mapreduce.WorkerService.ReceiveShuffleData:input_type -> mapreduce.ShuffleRequest
	13, // 21: mapreduce.MasterService.Heartbeat:output_type -> mapreduce.HeartbeatResponse
	15, // 22: mapreduce.MasterService.ReportTaskResult:output_type -> mapreduce.TaskResultAck
	20, // 23: mapreduce.WorkerService.Ping:output_type -> mapreduce.PingResponse
	11, // 24: mapreduce.WorkerService.AssignTask:output_type -> mapreduce.TaskAssignmentAck
	18, // 25: mapreduce.WorkerService.ReceiveShuffleData:output_type -> mapreduce.ShuffleResponse
	21, // [21:26] is the sub-list for method output_type
	16, // [16:21] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_mapreduce_proto_init() }
func file_proto_mapreduce_proto_init() {
	if File_proto_mapreduce_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mapreduce_proto_rawDesc), len(file_proto_mapreduce_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_mapreduce_proto_goTypes,
		DependencyIndexes: file_proto_mapreduce_proto_depIdxs,
		EnumInfos:         file_proto_mapreduce_proto_enumTypes,
		MessageInfos:      file_proto_mapreduce_proto_msgTypes,
	}.Build()
	File_proto_mapreduce_proto = out.File
	file_proto_mapreduce_proto_goTypes = nil
	file_proto_mapreduce_proto_depIdxs = nil
}
